### ISSUE TITLE
Registry format / layout

### ISSUE THREAD

**Issue by awvwgk** [fortran-lang/fpm-registry#18]
I just checked out this registry for fpm and noticed some rough edges. It is somewhat related to #1, but maybe worth a separate issue.

Specifying a project with multiple releases quickly gets redundant, imagine a package which releases on a regular basis, keeping the registry data up-to-date will quickly become a copy-and-paste approach
```toml
[project-name]
"1" = {git="https://github.com/project-name/project-name", tag="v1"}
"2" = {git="https://github.com/project-name/project-name", tag="v2"}
"2.1" = {git="https://github.com/user-name/project-name", tag="v2-server.1"}
"3" = {git="https://github.com/project-name/project-name", tag="v3"}
"3.1" = {git="https://github.com/project-name/project-name", tag="v3.1"}
"4" = {git="https://github.com/project-name/project-name", tag="v4"}
"latest" = {git="https://github.com/project-name/project-name", branch="main"}
```

A slight improvement in my opinion would be to allow specifying the upstream URL in the project section and allow to overwrite it per version basis.

```toml
[project-name]
git = "https://github.com/project-name/project-name"
"1" = {tag="v1"}
"2" = {tag="v2"}
"2.1" = {git="https://github.com/user-name/project-name", tag="v2-server.1"}
"3" = {tag="v3"}
"3.1" = {tag="v3.1"}
"4" = {tag="v4"}
latest.branch = "main"
```

**Comment by certik** [comment]
The other idea I had was that it would automatically convert the version number "3.1" to a tag "v3.1". But others thought that might be too fragile, so we haven't implemented it. I still think it's a good idea to make this simpler and we should implement it. Your example could become:
```toml
[project-name]
git = "https://github.com/project-name/project-name"
version_tags = ["1", "2", "3", "3.1", "4"]
"2.1" = {git="https://github.com/user-name/project-name", tag="v2-server.1"}
latest.branch = "main"
```
