### ISSUE TITLE
Add `fortran-lang/stdlib` package (branch: stdlib-fpm)

### ISSUE THREAD

**Issue by zoziha** [fortran-lang/fpm-registry#54]
Originally, I wanted to submit `fftpack` (has been passed, #53 ) and `stdlib-fpm` together, but found that it seems that `fpm-registry` does **not support `branch` analysis** like this:

```toml
[stdlib]
"latest" = { git = "https://github.com/fortran-lang/stdlib", branch = "stdlib-fpm" }
```

Is this an issue?

**Comment by awvwgk** [comment]
Try pretending it is a tag and try again, in git there is no practical difference between the two.

**Comment by zoziha** [comment]
I tried to submit #55 , and an error occurred in CI (see [CI failed](https://github.com/fortran-lang/fpm-registry/pull/55/checks?check_run_id=3630091554)). @awvwgk  Maybe I misunderstood what you mean.
Do you mean so:

```toml
[stdlib]
"latest" = { git = "https://github.com/fortran-lang/stdlib", tag = "stdlib-fpm" }
```

or,

```toml
[stdlib]
"latest" = { git = "https://github.com/fortran-lang/stdlib", branch = "stdlib-fpm" }
```
